@startuml
'https://plantuml.com/sequence-diagram

participant "etudiant:Etudiant" as Etudiant
participant "matiere:Set" as Set
participant "form:Formation" as Form

main -> Etudiant : calculerAvgGen()
activate Etudiant



Etudiant -> Form : getMatiere()
activate Form
Form --> Set : Set
deactivate Form

Etudiant -> Set : containsKey(matiere)
activate Set
Set --> Etudiant
deactivate Set
loop for(Etudiant e : this.etudiant)

Etudiant -> Etudiant : calculerAvgMat()
Etudiant -->Etudiant : moyAct

Etudiant -> Form : getCoef(v)
activate Form
Form --> Etudiant : coef
deactivate Form


end

Etudiant --> main : moyGenMAt

@enduml